//! Writing the extracted database out as reviewable TOML (`DB-002`, #126).
//!
//! The output is committed to the tree and reviewed as a pull-request diff, so
//! it is written by hand rather than by a serializer: comments explaining what
//! each table is, one row per line where a row is short enough to read, and a
//! stable order so that a regeneration which changes one key range shows one
//! changed line.
//!
//! It is also written to be *checked*. `kmsrs-db`'s `build.rs` reads this file
//! and fails the build on any invariant violation (`DB-004`, #128), so the file
//! is the contract between a human review and a compile-time guarantee.

use crate::model::Database;
use std::fmt::Write as _;

/// Render the database as TOML.
///
/// # Errors
///
/// Returns an error only if formatting into a `String` fails, which it does not.
#[must_use]
pub fn to_toml(database: &Database, generator_version: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "# Product data extracted from Microsoft licensing artifacts.\n\
         #\n\
         # GENERATED FILE — do not edit by hand. Regenerate with `kmsrs-dbgen`\n\
         # (see crates/kmsrs-dbgen/README.md) and review the diff.\n\
         #\n\
         # Every row names the source it came from. Data ships through this\n\
         # pipeline or it does not ship (declined item D19): hand-copying values\n\
         # out of another emulator's catalogue is the practice that produced\n\
         # every fabricated GUID the audits found.\n\
         #\n\
         # Generated by kmsrs-dbgen {generator_version}."
    );

    let _ = writeln!(out, "\n[meta]\ngenerator_version = \"{generator_version}\"");

    let _ = writeln!(
        out,
        "\n# The artifacts this file was extracted from. `sha256` is over the\n\
         # artifact as fetched, so a silently republished file is visible as a\n\
         # changed digest rather than as changed data.\n\
         #\n\
         # `application` is the one inference the pipeline makes: a pkeyconfig\n\
         # document names no application, so a Windows image's product table is\n\
         # attributed to Windows and an Office pack's to Office. It is recorded\n\
         # here rather than copied silently onto each row."
    );
    for source in &database.sources {
        let _ = writeln!(out, "\n[[source]]");
        let _ = writeln!(out, "id = {}", quote(&source.id));
        let _ = writeln!(out, "description = {}", quote(&source.description));
        let _ = writeln!(out, "origin = {}", quote(&source.origin));
        let _ = writeln!(out, "sha256 = {}", quote(&source.sha256));
        if let Some(application) = source.application {
            let _ = writeln!(out, "application = {}", quote(&application.to_string()));
        }
    }

    let _ = writeln!(
        out,
        "\n# The three KMS application GUIDs. A client sends one of these, and it\n\
         # is what decides whether a request is about Windows or about Office —\n\
         # the SKU ID never is (`KMS-018`, #34)."
    );
    for application in &database.applications {
        let _ = writeln!(out, "\n[[application]]");
        let _ = writeln!(out, "guid = {}", quote(&application.guid.to_string()));
        let _ = writeln!(out, "name = {}", quote(&application.name));
        let _ = writeln!(out, "source = {}", quote(&application.source));
    }

    let _ = writeln!(
        out,
        "\n# Product key configurations, transcribed from pkeyconfig and joined\n\
         # to their KMS host licence where one exists.\n\
         #\n\
         # Every key type is here, not only the CSVLKs: `Volume:GVLK`,\n\
         # `Volume:MAK`, `Retail`, the `OEM:` kinds and the evaluation types.\n\
         # The distinction between them is what the product gate is built on\n\
         # (`POL-010`, #98), and a row present in the artifact but absent here\n\
         # is a row somebody will later re-derive by hand.\n\
         #\n\
         # `counted_ids` is what the server actually decides on: a request's\n\
         # KMSID grants or refuses activation, while its ActID is ignored\n\
         # (`KMS-018`, #34). It is empty for everything that is not a CSVLK.\n\
         #\n\
         # `key_blocks` is a list, not a min/max pair. Windows Server 2022's\n\
         # CSVLK has two valid blocks with an invalid hole between them, and a\n\
         # min/max model emits key IDs inside the hole (`ID-019`, #124)."
    );
    for product in &database.products {
        write_product(&mut out, product);
    }

    out
}

/// Render one product row.
///
/// Split out because the file's shape is easier to check when the per-row
/// writing is not buried inside the document-level scaffolding.
fn write_product(out: &mut String, product: &crate::model::Product) {
    let _ = writeln!(out, "\n[[product]]");
    let _ = writeln!(
        out,
        "activation_id = {}",
        quote(&product.activation_id.to_string())
    );
    let _ = writeln!(out, "group_id = {}", product.group_id);
    let _ = writeln!(out, "description = {}", quote(&product.description));
    let _ = writeln!(out, "edition_id = {}", quote(&product.edition_id));
    let _ = writeln!(out, "key_type = {}", quote(&product.key_type));
    if let Some(application) = product.application {
        let _ = writeln!(out, "application = {}", quote(&application.to_string()));
    }
    if let Some(minutes) = product.cmid_expiration_minutes {
        let _ = writeln!(out, "cmid_expiration_minutes = {minutes}");
    }
    let _ = writeln!(out, "source = {}", quote(&product.source));
    if let Some(licence_source) = &product.licence_source {
        let _ = writeln!(out, "licence_source = {}", quote(licence_source));
    }

    if product.counted_ids.is_empty() {
        let _ = writeln!(out, "counted_ids = []");
    } else {
        let _ = writeln!(out, "counted_ids = [");
        for counted in &product.counted_ids {
            let _ = writeln!(out, "    {},", quote(&counted.to_string()));
        }
        let _ = writeln!(out, "]");
    }

    for block in &product.key_blocks {
        let _ = writeln!(
            out,
            "[[product.key_blocks]]\npart_number = {}\nstart = {}\nend = {}",
            quote(&block.part_number),
            block.start,
            block.end
        );
    }
}

/// Quote a string as a TOML basic string.
fn quote(value: &str) -> String {
    let mut out = String::with_capacity(value.len().saturating_add(2));
    out.push('"');
    for character in value.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            other if (other as u32) < 0x20 => {
                let _ = write!(out, "\\u{:04X}", other as u32);
            }
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    #![allow(
        clippy::unwrap_used,
        clippy::panic,
        clippy::indexing_slicing,
        clippy::arithmetic_side_effects,
        reason = "test code: a failed expectation should abort loudly"
    )]

    use super::{quote, to_toml};
    use crate::guid::Guid;
    use crate::model::{Application, Database, KeyBlock, Product, Source};

    fn sample() -> Database {
        Database {
            sources: vec![Source {
                id: "windows-server-2025".to_owned(),
                description: "Windows Server 2025 (26100) servercore image".to_owned(),
                origin: "mcr.microsoft.com/windows/servercore:ltsc2025".to_owned(),
                sha256: "abc123".to_owned(),
                application: Some(Guid::parse("55c92734-d682-4d71-983e-d6ec3f16059f").unwrap()),
            }],
            applications: vec![Application {
                guid: Guid::parse("55c92734-d682-4d71-983e-d6ec3f16059f").unwrap(),
                name: "Windows".to_owned(),
                source: "windows-server-2025".to_owned(),
            }],
            products: vec![Product {
                activation_id: Guid::parse("84e331f6-4279-48c4-ab10-b75139181351").unwrap(),
                group_id: 4919,
                edition_id: "ServerDatacenter".to_owned(),
                description: "Windows Server 2025".to_owned(),
                key_type: "Volume:CSVLK".to_owned(),
                key_blocks: vec![
                    KeyBlock {
                        part_number: "B".to_owned(),
                        start: 0,
                        end: 19999,
                    },
                    KeyBlock {
                        part_number: "A".to_owned(),
                        start: 20000,
                        end: 20_019_999,
                    },
                ],
                application: Some(Guid::parse("55c92734-d682-4d71-983e-d6ec3f16059f").unwrap()),
                counted_ids: vec![Guid::parse("907f1f65-adcd-4a2e-95bc-4bf500bc6e58").unwrap()],
                cmid_expiration_minutes: Some(43200),
                source: "windows-server-2025".to_owned(),
                licence_source: Some("windows-server-2025".to_owned()),
            }],
        }
    }

    #[test]
    fn the_output_is_valid_toml_and_round_trips_the_data() {
        let rendered = to_toml(&sample(), "0.1.0");
        let parsed: toml::Table = toml::from_str(&rendered).unwrap();

        assert_eq!(parsed["meta"]["generator_version"].as_str(), Some("0.1.0"));

        let product = &parsed["product"].as_array().unwrap()[0];
        assert_eq!(product["group_id"].as_integer(), Some(4919));
        assert_eq!(product["cmid_expiration_minutes"].as_integer(), Some(43200));
        assert_eq!(
            product["counted_ids"].as_array().unwrap()[0].as_str(),
            Some("907f1f65-adcd-4a2e-95bc-4bf500bc6e58")
        );

        let blocks = product["key_blocks"].as_array().unwrap();
        assert_eq!(blocks.len(), 2, "both blocks survive, unmerged");
        assert_eq!(blocks[0]["start"].as_integer(), Some(0));
        assert_eq!(blocks[1]["end"].as_integer(), Some(20_019_999));
    }

    /// The file is reviewed as a diff, so the same database must render
    /// byte-identically every time.
    #[test]
    fn rendering_is_deterministic() {
        assert_eq!(to_toml(&sample(), "0.1.0"), to_toml(&sample(), "0.1.0"));
    }

    /// Every row carries a source, because that is what "provenance-stamped"
    /// means in practice (`DB-002`, #126).
    #[test]
    fn every_row_names_its_source() {
        let rendered = to_toml(&sample(), "0.1.0");
        let parsed: toml::Table = toml::from_str(&rendered).unwrap();
        for table in ["application", "product"] {
            for row in parsed[table].as_array().unwrap() {
                assert!(row.get("source").is_some(), "{table} row without a source");
            }
        }
    }

    #[test]
    fn quoting_survives_the_characters_microsoft_actually_uses() {
        // Part numbers contain brackets; descriptions contain semicolons and
        // parentheses. None need escaping, but backslashes and quotes would.
        assert_eq!(quote("[Ge]X23-56798"), "\"[Ge]X23-56798\"");
        assert_eq!(quote(r#"a"b\c"#), r#""a\"b\\c""#);
        assert_eq!(quote("line\nbreak"), "\"line\\nbreak\"");
    }
}
