//! Golden wire vectors, committed as files (`TEST-002`, #223).
//!
//! # What these are, and what they are not
//!
//! Every vector here is **generated by this workspace's own encoders** from a
//! fixed deterministic entropy stream, then committed. That makes them
//! *regression* vectors: they lock the bytes, so a change that alters anything
//! on the wire fails a test instead of quietly shipping.
//!
//! They are **not** independent confirmation that the bytes are correct. A
//! vector produced by the code under test proves only self-consistency, and it
//! is worth being plain about which of the two properties any given file has:
//!
//! * **Independently confirmed** — the crypto layer. Its known-answer tests were
//!   generated by compiling vlmcsd's own `crypto.c` against a harness (see
//!   `tools/vlmcsd_crypto_vectors.c`), and the harness emits the FIPS-197 §C.1
//!   vector first to validate its own build. Those live in `kmsrs-crypto`
//!   (`TEST-001`, #222).
//! * **Self-consistent only** — the RPC framing in this crate. Capturing a real
//!   Windows KMS host's `bind_ack` would upgrade these, and until someone does,
//!   the doc comment should not imply otherwise.
//!
//! The same corpus seeds the fuzzers (`TEST-006`, #227), where being
//! *representative* matters more than being independently correct.
//!
//! # Regenerating
//!
//! `KMSRSOS_BLESS=1 cargo test -p kmsrs-proto --test golden_vectors`
//!
//! Blessing is deliberately a separate, explicit step. A test that rewrote its
//! own expectations on failure would assert nothing at all.

//! # Fuzz targets
//!
//! [`targets`] holds the body of each `cargo fuzz` target as an ordinary
//! function, for the reason documented there: a stable toolchain must be able
//! to compile and lint them (`SEC-004`, #196).

#![no_std]

extern crate alloc;

pub mod targets;

/// One committed vector.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Vector {
    /// The file's stem, which is also the name the test uses.
    pub name: &'static str,
    /// What this PDU is, for a failure message.
    pub description: &'static str,
    /// The bytes, exactly as committed.
    pub bytes: &'static [u8],
}

/// Every committed vector.
///
/// The twelve families `TEST-002` (#223) lists: `bind` and `bind_ack` in both
/// transfer syntaxes, `alter_context` and its response, a request and response
/// for each of v4, v5 and v6, a `fault`, and a `bind_nak`.
pub const VECTORS: &[Vector] = &[
    Vector {
        name: "bind-ndr32",
        description: "a client bind offering NDR32 only",
        bytes: include_bytes!("../vectors/bind-ndr32.bin"),
    },
    Vector {
        name: "bind-ndr64",
        description: "a client bind offering NDR32, NDR64 and feature negotiation",
        bytes: include_bytes!("../vectors/bind-ndr64.bin"),
    },
    Vector {
        name: "bind-ack-ndr32",
        description: "the host's bind_ack accepting NDR32",
        bytes: include_bytes!("../vectors/bind-ack-ndr32.bin"),
    },
    Vector {
        name: "bind-ack-ndr64",
        description: "the host's bind_ack accepting NDR64 and acknowledging BTFN",
        bytes: include_bytes!("../vectors/bind-ack-ndr64.bin"),
    },
    Vector {
        name: "alter-context",
        description: "a client alter_context on an established association",
        bytes: include_bytes!("../vectors/alter-context.bin"),
    },
    Vector {
        name: "alter-context-response",
        description: "the host's alter_context_response, which advertises no endpoint",
        bytes: include_bytes!("../vectors/alter-context-response.bin"),
    },
    // `WIRE-031` (#358): the same two exchanges with `PFC_CONC_MPX` set, which
    // is what a real client sends and what none of the vectors above did.
    //
    // The flag is the one thing a host echoes from the client's header, and it
    // is echoed on a `bind_ack` and **not** on an `alter_context_response`.
    // Until these existed nothing exercised either half, and a bug that echoed
    // it onto both shipped and passed the whole suite.
    Vector {
        name: "bind-ndr64-multiplex",
        description: "a client bind asking for multiplexing, as a real client does",
        bytes: include_bytes!("../vectors/bind-ndr64-multiplex.bin"),
    },
    Vector {
        name: "bind-ack-ndr64-multiplex",
        description: "the host's bind_ack, which echoes PFC_CONC_MPX",
        bytes: include_bytes!("../vectors/bind-ack-ndr64-multiplex.bin"),
    },
    Vector {
        name: "alter-context-multiplex",
        description: "a client alter_context still asking for multiplexing",
        bytes: include_bytes!("../vectors/alter-context-multiplex.bin"),
    },
    Vector {
        name: "alter-context-response-multiplex",
        description: "the host's alter_context_response, which does NOT echo PFC_CONC_MPX",
        bytes: include_bytes!("../vectors/alter-context-response-multiplex.bin"),
    },
    Vector {
        name: "request-v4",
        description: "a v4 activation request",
        bytes: include_bytes!("../vectors/request-v4.bin"),
    },
    Vector {
        name: "response-v4",
        description: "a v4 activation response, with its Rijndael-160 CBC-MAC",
        bytes: include_bytes!("../vectors/response-v4.bin"),
    },
    Vector {
        name: "request-v5",
        description: "a v5 activation request",
        bytes: include_bytes!("../vectors/request-v5.bin"),
    },
    Vector {
        name: "response-v5",
        description: "a v5 activation response, whose wire IV echoes the request's",
        bytes: include_bytes!("../vectors/response-v5.bin"),
    },
    Vector {
        name: "request-v6",
        description: "a v6 activation request",
        bytes: include_bytes!("../vectors/request-v6.bin"),
    },
    Vector {
        name: "response-v6",
        description: "a v6 activation response, with a fresh IV, hardware ID and HMAC",
        bytes: include_bytes!("../vectors/response-v6.bin"),
    },
    Vector {
        name: "fault",
        description: "a fault PDU for a call on an unaccepted context",
        bytes: include_bytes!("../vectors/fault.bin"),
    },
    Vector {
        name: "bind-nak",
        description: "a bind_nak refusing an unsupported RPC version",
        bytes: include_bytes!("../vectors/bind-nak.bin"),
    },
];

/// Look one up by name.
#[must_use]
pub fn find(name: &str) -> Option<&'static Vector> {
    let mut index = 0_usize;
    while index < VECTORS.len() {
        match VECTORS.get(index) {
            Some(vector) if str_eq(vector.name, name) => return Some(vector),
            _ => {}
        }
        index = index.saturating_add(1);
    }
    None
}

/// Compare two strings without `PartialEq` on `str` in a `const`-friendly way.
fn str_eq(left: &str, right: &str) -> bool {
    left.as_bytes() == right.as_bytes()
}
