//! Golden wire vectors, committed as files rather than generated (`TEST-002`,
//! #223).
//!
//! A vector generated by the code under test proves only that the code is
//! self-consistent. These are captured from real exchanges and from the two
//! reference implementations, committed, and read back byte-for-byte — so a
//! change that alters a byte on the wire fails a test instead of quietly
//! shipping. The same corpus seeds the fuzzers (`TEST-006`, #227).
