//! Compile the committed product data into `static` Rust tables
//! (`DB-003`, #127) and check every invariant while doing it
//! (`DB-004`, #128).
//!
//! # Why this is a build step and not runtime parsing
//!
//! py-kms parses its 88 KB XML catalogue **twice per activation**, which is
//! roughly 4 ms of pure XML parsing on the request path. Here the parsing
//! happens once, on a developer's machine, and what ships is an array in
//! read-only data.
//!
//! # Why the validation is here
//!
//! Every data defect the audits found is of one shape: a value that was wrong
//! and that nothing checked. `EPidIndex = 250` against a catalogue of far fewer
//! CSVLKs is a remotely-triggerable heap over-read in vlmcsd; py-kms ships 296
//! SKU entries with 287 unique IDs, so nine of them are unreachable. Both are
//! properties a build can check in a millisecond, and neither implementation
//! checks them at all.
//!
//! A failure here stops the build. That is the point: `DB-006` (#130) says
//! reject rather than skip, and the build is the last place a bad row can be
//! rejected before it becomes a wrong answer on the wire.
//!
//! It is not the only place. `crates/kmsrs-db/tests/data_integrity.rs`
//! (`TEST-007`, #228) checks the *shipped tables* for what neither this script
//! nor the generated `const` block can express — table floors, cross-table
//! agreement, date plausibility, and provenance. A `products.toml` with three
//! products in it parses here, sorts, and passes every index assertion; what it
//! fails is being the database.
//!
//! # About the lint relaxation
//!
//! `ARCH-008` (#8) denies panicking constructs, because a panic in the server
//! is a request a client can use to kill a connection. A build script has the
//! opposite property: panicking is its *only* failure mechanism, the message is
//! the diagnostic a maintainer reads, and none of this code exists in the
//! shipped binary. `expect_used` and friends are therefore allowed here and
//! nowhere else outside tests.
#![allow(
    clippy::panic,
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    reason = "a build script fails by panicking; none of this reaches the binary"
)]

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::Path;

/// Where the committed data lives, relative to the crate root.
const DATA: &str = "data/products.toml";

fn main() {
    println!("cargo::rerun-if-changed={DATA}");
    println!("cargo::rerun-if-changed=build.rs");

    let text =
        std::fs::read_to_string(DATA).unwrap_or_else(|error| panic!("cannot read {DATA}: {error}"));
    let document: toml::Table =
        toml::from_str(&text).unwrap_or_else(|error| panic!("cannot parse {DATA}: {error}"));

    let generated = generate(&document);

    let out_dir = std::env::var("OUT_DIR").expect("cargo always sets OUT_DIR");
    let path = Path::new(&out_dir).join("tables.rs");
    std::fs::write(&path, generated)
        .unwrap_or_else(|error| panic!("cannot write {}: {error}", path.display()));
}

/// A parsed product row, in the order the tables need it.
struct Product {
    activation_id: [u8; 16],
    activation_text: String,
    group_id: u32,
    description: String,
    edition_id: String,
    key_type: String,
    application: Option<[u8; 16]>,
    counted_ids: Vec<[u8; 16]>,
    key_blocks: Vec<(u32, u32)>,
}

fn generate(document: &toml::Table) -> String {
    let applications = read_applications(document);
    let products = read_products(document, &applications);

    let mut out = String::new();
    out.push_str(
        "// GENERATED by build.rs from data/products.toml. Do not edit.\n\
         //\n\
         // Every table is sorted by its key so it can be binary-searched, and\n\
         // that ordering is asserted below at compile time rather than assumed.\n\n",
    );

    write_applications(&mut out, &applications);
    write_products(&mut out, &products);
    write_csvlks(&mut out, &products);
    write_counted_ids(&mut out, &products);
    write_host_builds(&mut out, document);
    write_lcids(&mut out, document);
    write_assertions(&mut out);
    out
}

/// One parsed host-build row.
struct HostBuildRow {
    build: u32,
    platform_id: u32,
    release_date: Option<(i32, u8, u8)>,
    use_for_epid: bool,
    ndr64: bool,
    description: String,
}

/// Emit the host-build table and the index of builds an ePID may claim.
fn write_host_builds(out: &mut String, document: &toml::Table) {
    let rows = document
        .get("host_build")
        .and_then(toml::Value::as_array)
        .unwrap_or_else(|| panic!("{DATA} has no [[host_build]] rows"));

    let mut builds: Vec<HostBuildRow> = rows
        .iter()
        .map(|row| {
            let build = integer(row, "build", "host_build");
            let platform_id = integer(row, "platform_id", "host_build");
            let release_date = row
                .get("release_date")
                .and_then(toml::Value::as_str)
                .map(|text| parse_date(text, build));
            let use_for_epid = row
                .get("use_for_epid")
                .and_then(toml::Value::as_bool)
                .unwrap_or(false);
            let ndr64 = row
                .get("ndr64")
                .and_then(toml::Value::as_bool)
                .unwrap_or_else(|| panic!("host build {build} has no ndr64 column"));

            // `ID-007` (#112): the release date is the lower bound for a
            // randomised activation date, so a build that can produce an ePID
            // must have one. Checking here means the failure names the build.
            assert!(
                !(use_for_epid && release_date.is_none()),
                "host build {build} is marked use_for_epid but has no release_date"
            );

            HostBuildRow {
                build,
                platform_id,
                release_date,
                use_for_epid,
                ndr64,
                description: field(row, "description", "host_build").to_owned(),
            }
        })
        .collect();
    builds.sort_by_key(|entry| entry.build);

    let mut seen = BTreeSet::new();
    for entry in &builds {
        assert!(
            seen.insert(entry.build),
            "host build {} appears twice",
            entry.build
        );
    }

    // `ID-011` (#116): the set an ePID draws from must be non-empty by
    // construction. vlmcsd achieves the same coupling with a `while (TRUE)`
    // loop that hangs at start-up when nothing matches.
    let epid_indices: Vec<usize> = builds
        .iter()
        .enumerate()
        .filter(|(_, entry)| entry.use_for_epid)
        .map(|(index, _)| index)
        .collect();
    assert!(
        !epid_indices.is_empty(),
        "no host build is marked use_for_epid, so no ePID could be generated"
    );

    let _ = writeln!(
        out,
        "/// Windows builds a generated ePID may claim, sorted by build number.\n\
         pub static HOST_BUILDS: [HostBuild; {}] = [",
        builds.len()
    );
    for entry in &builds {
        let date = entry.release_date.map_or_else(
            || "None".to_owned(),
            |(year, month, day)| {
                // `Date::new` returns an `Option`, and a date that failed to
                // validate here would already have panicked above.
                format!("Date::new({year}, {month}, {day})")
            },
        );
        let _ = writeln!(
            out,
            "    HostBuild {{ build: {}, platform_id: {}, release_date: {date}, \
             use_for_epid: {}, ndr64: {}, description: {:?} }},",
            number_literal(entry.build),
            number_literal(entry.platform_id),
            entry.use_for_epid,
            entry.ndr64,
            entry.description
        );
    }
    out.push_str("];\n\n");

    let list = epid_indices.iter().fold(String::new(), |mut acc, index| {
        let _ = write!(acc, "{index}, ");
        acc
    });
    let _ = writeln!(
        out,
        "/// Indices into [`HOST_BUILDS`] of the builds an ePID may claim.\n\
         ///\n\
         /// Non-empty by construction: the build fails if it would be empty.\n\
         pub static EPID_HOST_BUILDS: [u16; {}] = [{list}];\n",
        epid_indices.len()
    );
}

/// Emit the locale table.
fn write_lcids(out: &mut String, document: &toml::Table) {
    let rows = document
        .get("lcid")
        .and_then(toml::Value::as_array)
        .unwrap_or_else(|| panic!("{DATA} has no [[lcid]] rows"));

    let mut locales: Vec<(u32, String, String, String)> = rows
        .iter()
        .map(|row| {
            let value = integer(row, "value", "lcid");
            // The research note that every LCID a real host reports is at least
            // 1025 is the same statement as the specific-culture filter in
            // `kmsrs-dbgen`; asserting it here catches a filter that regressed.
            assert!(value >= 1025, "LCID {value} is a primary language id");
            (
                value,
                field(row, "tag", "lcid").to_owned(),
                field(row, "language", "lcid").to_owned(),
                field(row, "location", "lcid").to_owned(),
            )
        })
        .collect();
    locales.sort_by_key(|entry| entry.0);

    let mut seen = BTreeSet::new();
    for entry in &locales {
        assert!(seen.insert(entry.0), "LCID {} appears twice", entry.0);
    }
    assert!(!locales.is_empty(), "{DATA} defines no locales");

    let _ = writeln!(
        out,
        "/// Locale identifiers a generated ePID may carry, sorted.\n\
         pub static LCIDS: [Lcid; {}] = [",
        locales.len()
    );
    for (value, tag, language, location) in &locales {
        let _ = writeln!(
            out,
            "    Lcid {{ value: {}, tag: {tag:?}, language: {language:?}, location: {location:?} }},",
            number_literal(*value)
        );
    }
    out.push_str("];\n\n");
}

/// A required integer field.
fn integer(row: &toml::Value, name: &str, table: &str) -> u32 {
    row.get(name)
        .and_then(toml::Value::as_integer)
        .and_then(|value| u32::try_from(value).ok())
        .unwrap_or_else(|| panic!("a [[{table}]] row has no usable {name}"))
}

/// Parse a `YYYY-MM-DD` date.
///
/// Upstream shipped one with a colon where the `T` belongs, which is the class
/// of defect a shape check catches for nothing.
fn parse_date(text: &str, build: u32) -> (i32, u8, u8) {
    let parts: Vec<&str> = text.split('-').collect();
    assert_eq!(
        parts.len(),
        3,
        "host build {build} has release_date {text:?}, which is not YYYY-MM-DD"
    );
    let year: i32 = parts[0]
        .parse()
        .unwrap_or_else(|_| panic!("host build {build}: bad year in {text:?}"));
    let month: u8 = parts[1]
        .parse()
        .unwrap_or_else(|_| panic!("host build {build}: bad month in {text:?}"));
    let day: u8 = parts[2]
        .parse()
        .unwrap_or_else(|_| panic!("host build {build}: bad day in {text:?}"));
    assert!(
        (1..=12).contains(&month) && (1..=31).contains(&day),
        "host build {build} has an impossible release_date {text:?}"
    );
    (year, month, day)
}

/// Read and validate the application table.
fn read_applications(document: &toml::Table) -> Vec<([u8; 16], String)> {
    let rows = document
        .get("application")
        .and_then(toml::Value::as_array)
        .unwrap_or_else(|| panic!("{DATA} has no [[application]] rows"));

    let mut applications: Vec<([u8; 16], String)> = rows
        .iter()
        .map(|row| {
            let guid = parse_guid(field(row, "guid", "application"));
            (guid, field(row, "name", "application").to_owned())
        })
        .collect();
    applications.sort();

    let unique: BTreeSet<&[u8; 16]> = applications.iter().map(|(guid, _)| guid).collect();
    assert_eq!(
        unique.len(),
        applications.len(),
        "duplicate application GUIDs in {DATA}"
    );
    assert!(
        !applications.is_empty(),
        "{DATA} must define at least one application"
    );
    applications
}

/// Read and validate the product table.
fn read_products(document: &toml::Table, applications: &[([u8; 16], String)]) -> Vec<Product> {
    let rows = document
        .get("product")
        .and_then(toml::Value::as_array)
        .unwrap_or_else(|| panic!("{DATA} has no [[product]] rows"));

    let known_applications: BTreeSet<[u8; 16]> =
        applications.iter().map(|(guid, _)| *guid).collect();

    let mut products: Vec<Product> = rows
        .iter()
        .map(|row| {
            let activation_text = field(row, "activation_id", "product").to_owned();
            let group_id = u32::try_from(
                row.get("group_id")
                    .and_then(toml::Value::as_integer)
                    .unwrap_or_else(|| panic!("product {activation_text} has no group_id")),
            )
            .unwrap_or_else(|_| panic!("product {activation_text} has an out-of-range group_id"));

            // vlmcsd ships entries with an empty GroupId and generates ePIDs
            // from them anyway. A group of zero is not a group.
            assert!(
                group_id > 0,
                "product {activation_text} has group_id 0, which cannot appear in an ePID"
            );

            let application = row
                .get("application")
                .and_then(toml::Value::as_str)
                .map(parse_guid);
            if let Some(application) = application {
                assert!(
                    known_applications.contains(&application),
                    "product {activation_text} names application {} , which is not in the \
                     application table",
                    format_guid(&application)
                );
            }

            let counted_ids: Vec<[u8; 16]> = row
                .get("counted_ids")
                .and_then(toml::Value::as_array)
                .map(|list| {
                    list.iter()
                        .map(|value| {
                            parse_guid(value.as_str().unwrap_or_else(|| {
                                panic!("product {activation_text} has a non-string counted id")
                            }))
                        })
                        .collect()
                })
                .unwrap_or_default();

            let key_blocks = read_key_blocks(row, &activation_text);

            Product {
                activation_id: parse_guid(&activation_text),
                activation_text,
                group_id,
                description: field(row, "description", "product").to_owned(),
                edition_id: field(row, "edition_id", "product").to_owned(),
                key_type: field(row, "key_type", "product").to_owned(),
                application,
                counted_ids,
                key_blocks,
            }
        })
        .collect();

    products.sort_by_key(|product| product.activation_id);

    // py-kms ships 296 SKU entries with 287 unique IDs, so nine are
    // unreachable — a lookup finds whichever the loader happened to keep.
    let mut seen = BTreeSet::new();
    for product in &products {
        assert!(
            seen.insert(product.activation_id),
            "duplicate activation id {} in {DATA}",
            product.activation_text
        );
    }

    products
}

/// Read and validate one product's key blocks.
fn read_key_blocks(row: &toml::Value, activation_text: &str) -> Vec<(u32, u32)> {
    let mut blocks: Vec<(u32, u32)> = row
        .get("key_blocks")
        .and_then(toml::Value::as_array)
        .map(|list| {
            list.iter()
                .map(|block| {
                    let read = |name: &str| {
                        u32::try_from(
                            block
                                .get(name)
                                .and_then(toml::Value::as_integer)
                                .unwrap_or_else(|| {
                                    panic!("key block for {activation_text} has no {name}")
                                }),
                        )
                        .unwrap_or_else(|_| {
                            panic!("key block for {activation_text} has an out-of-range {name}")
                        })
                    };
                    (read("start"), read("end"))
                })
                .collect()
        })
        .unwrap_or_default();

    blocks.sort_unstable();
    blocks.dedup();

    for (start, end) in &blocks {
        assert!(
            start <= end,
            "key block for {activation_text} runs backwards: {start}..={end}"
        );
    }

    blocks
}

/// Whether a product's key blocks overlap.
///
/// Only enforced for host keys; see [`write_csvlks`].
fn blocks_overlap(blocks: &[(u32, u32)]) -> Option<u32> {
    let mut previous_end: Option<u32> = None;
    for (start, end) in blocks {
        if let Some(previous) = previous_end
            && *start <= previous
        {
            return Some(*start);
        }
        previous_end = Some(*end);
    }
    None
}

/// Map Microsoft's product key type string onto the kind the policy layer uses.
///
/// An unrecognised string stops the build. A new key type in a future artifact
/// is something to look at, not something to silently file under "other".
fn key_kind(key_type: &str, activation_text: &str) -> &'static str {
    match key_type {
        "Volume:CSVLK" => "KmsHost",
        "Volume:GVLK" => "KmsClient",
        "Volume:MAK" => "MultipleActivation",
        "Retail" => "Retail",
        "Retail:TB:Eval" => "Evaluation",
        "OEM:DM" | "OEM:NONSLP" | "OEM:SLP" | "OEM:COA" => "OriginalEquipment",
        // Observed on Windows Server 2019 and 2025 entries. Neither appears in
        // any KMS counted-ID list, so nothing in the protocol turns on them;
        // they are kept as `Other` with the raw string preserved rather than
        // guessed at.
        "VT:IA" | "PGS:TB" => "Other",
        unknown => panic!(
            "product {activation_text} has key type {unknown:?}, which build.rs does not \
             recognise. Add it to key_kind() deliberately rather than letting it fall \
             through (DB-006, #130)."
        ),
    }
}

fn write_applications(out: &mut String, applications: &[([u8; 16], String)]) {
    let _ = writeln!(
        out,
        "/// The KMS applications, sorted by GUID.\n\
         ///\n\
         /// A request's `AppID` is what decides whether it is about Windows or\n\
         /// about Office. Its `ActID` never is (`KMS-018`, #34).\n\
         pub static APPLICATIONS: [Application; {}] = [",
        applications.len()
    );
    for (guid, name) in applications {
        let _ = writeln!(
            out,
            "    Application {{ guid: {}, name: {name:?} }},",
            guid_literal(guid)
        );
    }
    out.push_str("];\n\n");
}

fn write_products(out: &mut String, products: &[Product]) {
    let _ = writeln!(
        out,
        "/// Every product key configuration, sorted by activation id.\n\
         pub static PRODUCTS: [Product; {}] = [",
        products.len()
    );
    for product in products {
        let kind = key_kind(&product.key_type, &product.activation_text);
        let _ = writeln!(
            out,
            "    Product {{ activation_id: {}, group_id: {}, kind: KeyKind::{kind}, \
             key_type: {:?}, edition_id: {:?}, description: {:?}, application: {} }},",
            guid_literal(&product.activation_id),
            number_literal(product.group_id),
            product.key_type,
            product.edition_id,
            product.description,
            option_guid_literal(product.application.as_ref())
        );
    }
    out.push_str("];\n\n");
}

fn write_csvlks(out: &mut String, products: &[Product]) {
    let csvlks: Vec<&Product> = products
        .iter()
        .filter(|product| product.key_type == "Volume:CSVLK")
        .collect();
    assert!(!csvlks.is_empty(), "{DATA} contains no CSVLK");

    let _ = writeln!(
        out,
        "/// KMS host keys, sorted by activation id.\n\
         ///\n\
         /// The subset of [`PRODUCTS`] a KMS host can hold. Each carries the\n\
         /// key-ID blocks a genuine host draws an ePID from and the counted IDs\n\
         /// it will answer for.\n\
         pub static CSVLKS: [Csvlk; {}] = [",
        csvlks.len()
    );
    for csvlk in &csvlks {
        // A CSVLK with no key block cannot produce an ePID, and the arithmetic
        // that would try divides by a zero-width range (`ID-015`, #120).
        assert!(
            !csvlk.key_blocks.is_empty(),
            "CSVLK {} has no key blocks, so no ePID can be generated for it",
            csvlk.activation_text
        );

        // Overlap matters here and only here: an ePID draws a key ID uniformly
        // across the union of a host key's blocks, and an overlap would bias
        // that draw towards the overlapping region — a distribution a detection
        // probe could measure (`TEST-008`, #229).
        //
        // It is *not* enforced for every product, because Microsoft's own data
        // contains an overlap: `Win 11 RTM CPC Retail` has a block covering
        // 0..=999999999 alongside 0..=9999 and 10000..=999999999. Nothing draws
        // a key ID from a retail SKU, so rejecting the whole database over it
        // would be enforcing a rule where it has no meaning.
        assert!(
            blocks_overlap(&csvlk.key_blocks).is_none(),
            "CSVLK {} has overlapping key blocks, which would bias the ePID key-ID draw",
            csvlk.activation_text
        );

        let blocks =
            csvlk
                .key_blocks
                .iter()
                .fold(String::new(), |mut accumulated, (start, end)| {
                    let _ = write!(
                        accumulated,
                        "KeyBlock {{ start: {}, end: {} }}, ",
                        number_literal(*start),
                        number_literal(*end)
                    );
                    accumulated
                });
        let counted = csvlk
            .counted_ids
            .iter()
            .fold(String::new(), |mut accumulated, guid| {
                let _ = write!(accumulated, "{}, ", guid_literal(guid));
                accumulated
            });
        let _ = writeln!(
            out,
            "    Csvlk {{ activation_id: {}, group_id: {}, description: {:?}, \
             application: {}, key_blocks: &[{blocks}], counted_ids: &[{counted}] }},",
            guid_literal(&csvlk.activation_id),
            number_literal(csvlk.group_id),
            csvlk.description,
            option_guid_literal(csvlk.application.as_ref())
        );
    }
    out.push_str("];\n\n");
}

fn write_counted_ids(out: &mut String, products: &[Product]) {
    let csvlk_index: BTreeMap<[u8; 16], u16> = products
        .iter()
        .filter(|product| product.key_type == "Volume:CSVLK")
        .enumerate()
        .map(|(index, product)| {
            (
                product.activation_id,
                u16::try_from(index).expect("far fewer than 65,536 CSVLKs"),
            )
        })
        .collect();

    let mut by_counted: BTreeMap<[u8; 16], Vec<u16>> = BTreeMap::new();
    for product in products {
        let Some(index) = csvlk_index.get(&product.activation_id) else {
            continue;
        };
        for counted in &product.counted_ids {
            by_counted.entry(*counted).or_default().push(*index);
        }
    }
    for indices in by_counted.values_mut() {
        indices.sort_unstable();
        indices.dedup();
    }

    let _ = writeln!(
        out,
        "/// KMS counted IDs, sorted, each mapped to the CSVLKs that count it.\n\
         ///\n\
         /// The mapping is many-to-many and that is not an accident of the\n\
         /// data: a Windows Server 2025 host key counts 22 products, and a\n\
         /// single product is counted by up to ten different host keys. A\n\
         /// model with one CSVLK per product — which is what both existing\n\
         /// emulators use — cannot represent that, so the choice of which host\n\
         /// key to answer as is a policy decision (`ID-002`, #107) rather than\n\
         /// a table lookup.\n\
         pub static COUNTED_IDS: [CountedId; {}] = [",
        by_counted.len()
    );
    for (guid, indices) in &by_counted {
        let list = indices
            .iter()
            .fold(String::new(), |mut accumulated, index| {
                let _ = write!(accumulated, "{index}, ");
                accumulated
            });
        let _ = writeln!(
            out,
            "    CountedId {{ guid: {}, csvlks: &[{list}] }},",
            guid_literal(guid)
        );
    }
    out.push_str("];\n\n");
}

/// Compile-time assertions over the generated tables (`DB-004`, #128).
///
/// These duplicate checks that `build.rs` already performed, deliberately: a
/// hand-edited `tables.rs`, or a future change to the emission code, would slip
/// past the build script but not past `const` evaluation.
fn write_assertions(out: &mut String) {
    out.push_str(
        r#"// Indexing and arithmetic are denied workspace-wide because they panic
// at *runtime*. There is no runtime here: this block is evaluated by the
// compiler, so an out-of-bounds index is a compile error, which is exactly the
// outcome these assertions exist to produce (`ARCH-008`, #8).
#[allow(
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    reason = "const evaluation: an out-of-bounds index is a compile error, not a panic"
)]
const _: () = {
    // Every table is binary-searched, so sortedness is load-bearing rather
    // than tidy. An unsorted table does not fail loudly; it silently fails to
    // find rows that are present.
    const fn sorted<const N: usize>(keys: [[u8; 16]; N]) -> bool {
        let mut index = 1;
        while index < N {
            let mut byte = 0;
            let mut ordered = false;
            while byte < 16 {
                if keys[index - 1][byte] < keys[index][byte] {
                    ordered = true;
                    byte = 16;
                } else if keys[index - 1][byte] > keys[index][byte] {
                    byte = 16;
                } else {
                    byte += 1;
                }
            }
            if !ordered {
                return false;
            }
            index += 1;
        }
        true
    }

    let mut application_keys = [[0u8; 16]; APPLICATIONS.len()];
    let mut index = 0;
    while index < APPLICATIONS.len() {
        application_keys[index] = APPLICATIONS[index].guid.to_bytes();
        index += 1;
    }
    assert!(sorted(application_keys), "APPLICATIONS is not sorted by GUID");

    let mut product_keys = [[0u8; 16]; PRODUCTS.len()];
    let mut index = 0;
    while index < PRODUCTS.len() {
        product_keys[index] = PRODUCTS[index].activation_id.to_bytes();
        index += 1;
    }
    assert!(sorted(product_keys), "PRODUCTS is not sorted by activation id");

    let mut counted_keys = [[0u8; 16]; COUNTED_IDS.len()];
    let mut index = 0;
    while index < COUNTED_IDS.len() {
        counted_keys[index] = COUNTED_IDS[index].guid.to_bytes();
        index += 1;
    }
    assert!(sorted(counted_keys), "COUNTED_IDS is not sorted by GUID");

    // vlmcsd never checks that an ePID index is inside its CSVLK table, and
    // `EPidIndex = 250` against a shorter table is a remotely-triggerable
    // over-read. Ours are generated, so the check is cheap and total.
    let mut index = 0;
    while index < COUNTED_IDS.len() {
        let csvlks = COUNTED_IDS[index].csvlks;
        assert!(!csvlks.is_empty(), "a counted ID maps to no CSVLK");
        let mut position = 0;
        while position < csvlks.len() {
            assert!(
                (csvlks[position] as usize) < CSVLKS.len(),
                "a counted ID references a CSVLK index past the end of the table"
            );
            position += 1;
        }
        index += 1;
    }

    // `ID-011` (#116) and `ID-010` (#115), asserted where they cannot be
    // edited out: there is always a build to draw from, every drawable build
    // has a release date, and no build claims a transfer syntax its era did
    // not have.
    assert!(!EPID_HOST_BUILDS.is_empty(), "no host build can produce an ePID");
    let mut index = 0;
    while index < EPID_HOST_BUILDS.len() {
        let build = &HOST_BUILDS[EPID_HOST_BUILDS[index] as usize];
        assert!(build.use_for_epid, "EPID_HOST_BUILDS names a build that is not one");
        assert!(build.release_date.is_some(), "a drawable build has no release date");
        index += 1;
    }
    assert!(!LCIDS.is_empty(), "no locale to draw from");

    // Every CSVLK must be able to produce an ePID.
    let mut index = 0;
    while index < CSVLKS.len() {
        assert!(!CSVLKS[index].key_blocks.is_empty(), "a CSVLK has no key blocks");
        assert!(CSVLKS[index].group_id > 0, "a CSVLK has group 0");
        index += 1;
    }
};
"#,
    );
}

/// A required string field, or a build failure naming what was missing.
fn field<'a>(row: &'a toml::Value, name: &str, table: &str) -> &'a str {
    row.get(name)
        .and_then(toml::Value::as_str)
        .unwrap_or_else(|| panic!("a [[{table}]] row has no {name}"))
}

/// Parse a canonical GUID string into bytes.
fn parse_guid(text: &str) -> [u8; 16] {
    let digits: String = text.chars().filter(|character| *character != '-').collect();
    assert_eq!(digits.len(), 32, "not a GUID: {text:?}");
    let mut bytes = [0_u8; 16];
    for (index, byte) in bytes.iter_mut().enumerate() {
        let start = index * 2;
        let pair = digits
            .get(start..start + 2)
            .unwrap_or_else(|| panic!("not a GUID: {text:?}"));
        *byte = u8::from_str_radix(pair, 16).unwrap_or_else(|_| panic!("not a GUID: {text:?}"));
    }
    bytes
}

/// Format bytes back into a canonical GUID string, for messages.
fn format_guid(bytes: &[u8; 16]) -> String {
    let mut out = String::new();
    for (index, byte) in bytes.iter().enumerate() {
        if matches!(index, 4 | 6 | 8 | 10) {
            out.push('-');
        }
        let _ = write!(out, "{byte:02x}");
    }
    out
}

/// Format a number with underscore separators.
///
/// The generated file is linted like any other, and `unreadable_literal` is on.
/// Emitting `20_019_999` rather than `20019999` also makes the table readable
/// when someone opens it to check a key range against the artifact.
fn number_literal(value: u32) -> String {
    let digits = value.to_string();
    let mut out = String::new();
    for (index, digit) in digits.chars().enumerate() {
        let remaining = digits.len() - index;
        if index > 0 && remaining.is_multiple_of(3) {
            out.push('_');
        }
        out.push(digit);
    }
    out
}

/// A `Guid::from_bytes([..])` expression.
fn guid_literal(bytes: &[u8; 16]) -> String {
    let mut out = String::from("Guid::from_bytes([");
    for byte in bytes {
        let _ = write!(out, "{byte:#04x}, ");
    }
    out.push_str("])");
    out
}

/// An `Option<Guid>` expression.
fn option_guid_literal(bytes: Option<&[u8; 16]>) -> String {
    bytes.map_or_else(
        || "None".to_owned(),
        |bytes| format!("Some({})", guid_literal(bytes)),
    )
}
