//! The product database: CSVLK groups, KMS IDs, GVLKs and host builds, as
//! `static` tables generated at build time (`ARCH-001`, #1; `DB-003`, #127).
//!
//! The tables are generated by `build.rs` from a reviewable data file that
//! [`kmsrs-dbgen`] extracts from Microsoft's own signed `pkeyconfig` artifacts.
//! Product data ships through that pipeline or it does not ship (`DB-002`,
//! #126) — hand-copying values out of another emulator's catalogue is the
//! practice that produced every fabricated GUID the audits found.
//!
//! This crate has no dependencies and no runtime initialisation. Every table is
//! a `static` in the binary's read-only data, and every invariant the data must
//! satisfy is checked at build time rather than on first use (`DB-004`, #128).
//!
//! [`kmsrs-dbgen`]: https://github.com/schlarpc/kmsrsos/tree/main/crates/kmsrs-dbgen

#![no_std]
