//! The product database: applications, product key configurations, KMS host
//! keys and KMS counted IDs, as `static` tables in the binary's read-only data
//! (`ARCH-001`, #1; `DB-003`, #127).
//!
//! The tables are generated by `build.rs` from `data/products.toml`, which
//! [`kmsrs-dbgen`] extracts from Microsoft's own signed licensing artifacts.
//! Product data ships through that pipeline or it does not ship (`DB-002`,
//! #126) — hand-copying values out of another emulator's catalogue is the
//! practice that produced every fabricated GUID the audits found.
//!
//! # No runtime work
//!
//! This crate has no dependencies, no allocator, no initialisation and no
//! locks. A lookup is a binary search over an array in `.rodata`. That is not
//! micro-optimisation: py-kms parses an 88 KB XML catalogue *twice per
//! activation*, roughly 4 ms of pure parsing before it has decided anything, and
//! it is also why the same code runs unchanged on the bare-metal target.
//!
//! # Invariants are checked when the binary is built
//!
//! Every data defect the audits found has the same shape — a value that was
//! wrong, and nothing that checked. `build.rs` rejects duplicate activation
//! IDs, overlapping or backwards key blocks, a zero group ID, an unknown
//! application reference and an unrecognised key type; the generated file then
//! re-asserts sortedness and index bounds under `const` evaluation, so a
//! hand-edited table does not slip past either (`DB-004`, #128).
//!
//! [`kmsrs-dbgen`]: https://github.com/schlarpc/kmsrsos/tree/main/crates/kmsrs-dbgen

#![no_std]

#[cfg(test)]
extern crate alloc;

pub mod date;
pub mod guid;
pub mod query;
pub mod tables;

pub use date::Date;
pub use guid::Guid;
pub use query::{
    application, csvlk, csvlk_at, csvlks_counting, epid_host_build_at, epid_host_build_count,
    epid_host_builds, is_known_counted_id, lcid_at, lcid_count, product,
};
pub use tables::{
    APPLICATIONS, Application, COUNTED_IDS, CSVLKS, CountedId, Csvlk, EPID_HOST_BUILDS,
    HOST_BUILDS, HostBuild, KeyBlock, KeyKind, LCIDS, Lcid, PRODUCTS, Product,
};
